### ISSUE TITLE
Most traits rendered "Invalid for CALC" by upgrade to kdxplore-prod-2.1.1.zip

### ISSUE THREAD

**Issue by kadreher** [kddart/kdxplore#14]
Greetings,

I downloaded and opened the new production version of KDX - 2.1.1. When I opened my list of traits most of them were shown in blue indicating that they are invalid for calculations even though many of them are integers. We would really like to be able to use these in formulae. How can I make these valid for CALC again?

Here's a screenshot:

![image](https://cloud.githubusercontent.com/assets/8202843/26758896/a8f1153a-48b2-11e7-98a8-ec3574e92722.png)

[traits_to_text.txt](https://github.com/kddart/kdxplore/files/1050113/traits_to_text.txt)

I also just exported the list of traits for you to see in case there are any errors in them.

Thanks in advance for your help with this.

**Comment by kadreher** [comment]
Hello,
I also just created a new trait within this instance of KDXplore - Trait 1 (attached). It is also appearing in blue as "Invalid for CALC." How can I create traits that will be valid for CALC?

[new_trait.txt](https://github.com/kddart/kdxplore/files/1050116/new_trait.txt)

Thank you for your help.

**Comment by Hearni** [comment]
I have the same issue - in my KDX many of the old traits are invalid for calc (integer and decimal) and when I add new decimal or integer traits they are also invalid for calc- what has happened? In the attached file I have just added test trait calc and test trait calc 2
![kdx calc issues](https://cloud.githubusercontent.com/assets/25251182/26801976/5dfae38c-4a04-11e7-9f40-514e2b8782ef.PNG)

**Comment by spelexander** [comment]
**You are unable to use Integer or Decimal traits in calc which have spaces in them.**

This exists to stop some logical inconsistencies in variable naming.
The formula parser reads spaces exactly as separators between operators and variables (Trait names).

Think about Traits which may have a name that is a subset of another name e.g.: "Trait" and "Trait 1".

KDXplore also doesn't allow Trait names which may represent some operation e.g. "Trait-1" could be interpreted as Trait minus 1.

**Imagine that you are using your variables (Trait names) in a formula in Excel. You would find similar behaviour. I recommend using Trait names with an underscore rather than space, if they are to be used in CALC traits.**

I have tested KDXplore back to 2.0.44 and found that this restriction was present since before 2.1.1

We may think of adding some functionality to automatically assist in changing Trait names on import, warning the user, or allowing Trait name representation in formulae in such a way that spaces could be allowed. However this is a topic for further discussion, as it may have implications to any future computational functionality that might be added to the CALC formulae builder.

**Comment by kadreher** [comment]
Hi Alex,

Thank you very much for your reply. I will go through Sarah’s response and try to get back to you on our Wednesday or Thursday.

Sincerely,
kate
